# Generated by Django 3.2 on 2024-12-17 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator(254), django.core.validators.RegexValidator('^[\\w.@+-]+\\Z'), django.core.validators.RegexValidator('^[^me]+$', message="Username cannot be 'me'")], verbose_name='Почта'),
        ),
    ]
