# Generated by Django 3.2 on 2024-12-17 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.RegexValidator('^[\\w.@+-]+\\Z')], verbose_name='Имя пользователя'),
        ),
    ]
